apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
    - name: volume-container-xfusion-1
      image: fedora:latest
      command: ["sleep", "10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/media
    - name: volume-container-xfusion-2
      image: fedora:latest
      command: ["sleep", "10000"]
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/games
